name: llms
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - ansi2html=1.9.2
  - anyio=4.8.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=25.1.0
  - aws-c-auth=0.8.1
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.9
  - aws-c-sdkutils=0.2.2
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.9
  - aws-sdk-cpp=1.11.489
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - backoff=2.2.1
  - beautifulsoup4=4.13.3
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - clickhouse-connect=0.8.15
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.11.11
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.8.57
  - cuda-cudart_linux-64=12.8.57
  - cuda-cuobjdump=12.8.55
  - cuda-cupti=12.8.57
  - cuda-nvcc-tools=12.8.61
  - cuda-nvdisasm=12.8.55
  - cuda-nvrtc=12.8.61
  - cuda-nvtx=12.8.55
  - cuda-nvvm-tools=12.8.61
  - cuda-version=12.8
  - cudnn=9.7.1.26
  - cusparselt=0.6.3.2
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dash=2.18.2
  - dbus=1.13.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dnspython=2.7.0
  - double-conversion=3.3.0
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - faiss=1.9.0
  - fastapi=0.115.8
  - fastapi-cli=0.0.7
  - filelock=3.17.0
  - flask=3.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.56.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - h11=0.14.0
  - h2=4.2.0
  - harfbuzz=10.2.0
  - hnswlib=0.8.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httptools=0.6.4
  - httpx=0.28.1
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-dash=0.4.2
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libarrow=19.0.0
  - libarrow-acero=19.0.0
  - libarrow-dataset=19.0.0
  - libarrow-substrait=19.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcublas=12.8.3.14
  - libcudss0=0.4.0.2
  - libcufft=11.3.3.41
  - libcufile=1.13.0.11
  - libcups=2.3.3
  - libcurand=10.3.9.55
  - libcurl=8.11.1
  - libcusolver=11.7.2.55
  - libcusparse=12.5.7.53
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libfaiss=1.9.0
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgoogle-cloud=2.34.0
  - libgoogle-cloud-storage=2.34.0
  - libgpg-error=1.51
  - libgrpc=1.67.1
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm19=19.1.7
  - liblzma=5.6.4
  - libmagma=2.8.0
  - libnghttp2=1.64.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libnvjitlink=12.8.61
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.18.0
  - libopentelemetry-cpp-headers=1.18.0
  - libparquet=19.0.0
  - libpciaccess=0.18
  - libpng=1.6.46
  - libpq=17.2
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - libsentencepiece=0.2.0
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libudev1=257.2
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - lz4=4.3.3
  - lz4-c=1.10.0
  - markdown-it-py=3.0.0
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.1
  - mkl=2024.2.2
  - monotonic=1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - narwhals=1.26.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - nccl=2.25.1.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.0
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=6.0.0
  - posthog=3.6.5
  - prometheus-cpp=1.3.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - protobuf=5.28.3
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pyarrow-core=19.0.0
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyparsing=3.2.1
  - pyside6=6.8.2
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.0.1
  - python-duckdb=1.1.3
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.1.24
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytorch=2.5.1
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - qt6-main=6.8.2
  - rdma-core=56.0
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - retrying=1.3.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - s2n=1.5.11
  - scikit-learn=1.6.1
  - send2trash=1.8.3
  - sentencepiece=0.2.0
  - sentencepiece-python=0.2.0
  - sentencepiece-spm=0.2.0
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.3
  - starlette=0.45.3
  - sympy=1.13.3
  - tbb=2021.13.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tokenizers=0.21.0
  - tomli=2.2.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triton=3.1.0
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - uvicorn=0.34.0
  - uvicorn-standard=0.34.0
  - uvloop=0.21.0
  - watchfiles=1.0.4
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=14.2
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - accelerate==1.3.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiohttp-retry==2.9.1
      - aiosignal==1.3.2
      - anthropic==0.45.2
      - asgiref==3.8.1
      - bcrypt==4.2.1
      - bitsandbytes==0.45.2
      - build==1.2.2.post1
      - cachetools==5.5.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - dataclasses-json==0.6.7
      - datasets==3.2.0
      - deprecated==1.2.18
      - dill==0.3.8
      - distro==1.9.0
      - durationpy==0.9
      - faiss-cpu==1.10.0
      - feedparser==6.0.11
      - ffmpy==0.5.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gensim==4.3.3
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.24.1
      - google-api-python-client==2.160.0
      - google-auth==2.38.0
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.4
      - googleapis-common-protos==1.67.0rc1
      - gradio==5.15.0
      - gradio-client==1.7.0
      - greenlet==3.1.1
      - grpcio==1.70.0
      - grpcio-status==1.70.0
      - grpclib==0.4.7
      - httplib2==0.22.0
      - httpx-sse==0.4.0
      - huggingface-hub==0.28.1
      - importlib-metadata==8.5.0
      - jiter==0.8.2
      - jsonpatch==1.33
      - kubernetes==32.0.0
      - langchain==0.3.18
      - langchain-chroma==0.2.1
      - langchain-community==0.3.17
      - langchain-core==0.3.34
      - langchain-openai==0.3.4
      - langchain-text-splitters==0.3.6
      - langsmith==0.3.8
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - mmh3==5.1.0
      - modal==0.73.31
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - oauthlib==3.2.2
      - ollama==0.4.7
      - onnxruntime==1.20.1
      - openai==1.61.1
      - opentelemetry-api==1.30.0
      - opentelemetry-exporter-otlp-proto-common==1.30.0
      - opentelemetry-exporter-otlp-proto-grpc==1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-asgi==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-proto==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opentelemetry-util-http==0.51b0
      - orjson==3.10.15
      - propcache==0.2.1
      - proto-plus==1.26.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic-settings==2.7.1
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rsa==4.9
      - ruff==0.9.6
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scipy==1.13.1
      - semantic-version==2.10.0
      - sentence-transformers==3.4.1
      - sgmllib3k==1.0.0
      - sigtools==4.0.1
      - smart-open==7.1.0
      - speedtest-cli==2.1.3
      - sqlalchemy==2.0.38
      - synchronicity==0.9.11
      - tenacity==9.0.0
      - tiktoken==0.8.0
      - toml==0.10.2
      - tomlkit==0.13.2
      - transformers==4.48.3
      - twilio==9.4.4
      - types-certifi==2021.10.8.3
      - types-toml==0.10.8.20240310
      - typing-inspect==0.9.0
      - uritemplate==4.1.1
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.18.3
